-- user
create table
  public.users (
    user_id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    username text not null,
    email text not null,
    password text not null,
    constraint Users_pkey primary key (user_id),
    constraint Users_email_key unique (email),
    constraint Users_username_key unique (username)
  ) tablespace pg_default;

-- profile_info
create table
  public.profile_info (
    user_id bigint generated by default as identity not null,
    level text not null default ''::text,
    about_me text not null default ''::text,
    logged_in boolean not null default false,
    constraint profile_info_pkey primary key (user_id)
  ) tablespace pg_default;

-- comments
create table
  public.comments (
    comment_id bigint generated by default as identity not null,
    user_id integer not null,
    recipe_id integer not null,
    comment text not null default ''::text,
    created_at timestamp with time zone not null default now(),
    constraint comments_pkey primary key (comment_id)
  ) tablespace pg_default;

-- favorites
create table
  public.favorites (
    recipe_id bigint generated by default as identity not null,
    user_id integer null,
    created_at timestamp with time zone not null default now(),
    constraint favorites_pkey primary key (recipe_id)
  ) tablespace pg_default;

-- ingredients
create table
  public.ingredients (
    ingredient_id bigint generated by default as identity not null,
    recipe_id integer null default '-1'::integer,
    name text not null default ''::text,
    measurement_type text not null default ''::text,
    amount integer not null default 0,
    constraint ingredients_pkey primary key (ingredient_id)
  ) tablespace pg_default;

-- recipes
reate table
  public.recipes (
    recipe_id bigint generated by default as identity not null,
    type text not null default ''::text,
    title text not null default ''::text,
    time_needed integer not null default 0,
    author_id integer not null,
    created_at timestamp with time zone not null default now(),
    complexity text not null default ''::text,
    is_public boolean not null default false,
    rating real null,
    rating_count integer null default 0,
    constraint recipes_pkey primary key (recipe_id)
  ) tablespace pg_default;

-- tags
create table
  public.tags (
    tag_id bigint generated by default as identity not null,
    recipe_id integer not null default '-1'::integer,
    tag text not null default ''::text,
    constraint tags_pkey primary key (tag_id)
  ) tablespace pg_default;
